version: '3.8'

services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - POSTGRES_HOST=nextcloud_db
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud_db_password_2024
      - NEXTCLOUD_ADMIN_USER=admin
      - NEXTCLOUD_ADMIN_PASSWORD=nextcloud_vgnc_2024
      - NEXTCLOUD_TRUSTED_DOMAINS=192.168.1.243
      - NEXTCLOUD_APPS_INSTALL=1
      - NEXTCLOUD_APPS_ENABLE=1
    volumes:
      - nextcloud_data:/var/www/html
      - nextcloud_apps:/var/www/html/custom_apps
      - nextcloud_config:/var/www/html/config
      - nextcloud_themes:/var/www/html/themes
    depends_on:
      - nextcloud_db
    networks:
      - nextcloud_network

  nextcloud_db:
    image: postgres:15
    container_name: nextcloud_postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=nextcloud
      - POSTGRES_USER=nextcloud
      - POSTGRES_PASSWORD=nextcloud_db_password_2024
    volumes:
      - nextcloud_db_data:/var/lib/postgresql/data
    networks:
      - nextcloud_network

  nextcloud_redis:
    image: redis:7-alpine
    container_name: nextcloud_redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - nextcloud_redis_data:/data
    networks:
      - nextcloud_network

volumes:
  nextcloud_data:
    driver: local
  nextcloud_apps:
    driver: local
  nextcloud_config:
    driver: local
  nextcloud_themes:
    driver: local
  nextcloud_db_data:
    driver: local
  nextcloud_redis_data:
    driver: local

networks:
  nextcloud_network:
    driver: bridge
