version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "8000:8000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    environment:
      - PORTAINER_EDITION=ce
    networks:
      - portainer_network

volumes:
  portainer_data:
    driver: local

networks:
  portainer_network:
    driver: bridge
